kind: pipeline
type: exec
name: Build Music Player
concurrency:
  limit: 1
platform:
  os: linux
  arch: amd64
steps:
  - name: build
    commands:
      - npm ci | sed $'s,\x1b\\[[0-9;]*[a-zA-Z],,g'
      - npm run build | sed $'s,\x1b\\[[0-9;]*[a-zA-Z],,g'
---
kind: pipeline
type: exec
name: Deploy Music Player
concurrency:
  limit: 1
platform:
  os: linux
  arch: amd64
steps:
  - name: deploy
    commands:
      - rm -rf /opt/www/audio/{css,fonts,img,js}
      - rm -f /opt/www/audio/index.html
      - cp -r dist/* /opt/www/audio/
      - chown -R itege:deployers /opt/www/audio/*
      - chmod -R 775 /opt/www/audio/*
    when:
      branch:
        - master
      status:
        - success
depends_on:
- Build Music Player