kind: pipeline
type: exec
name: Build & Deploy Music Player
concurrency:
  limit: 1
platform:
  os: linux
  arch: amd64
steps:
  - name: build
    commands:
      - yarn
      - yarn build
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
  - name: deploy
    commands:
      - rm -rf /opt/www/audio/{css,fonts,img,js}
      - rm -f /opt/www/audio/index.html
      - cp -r dist/* /opt/www/audio/
      - chown -R itege:deployers /opt/www/audio/*
      - chmod -R 775 /opt/www/audio/*
    when:
      branch:
        - master
      status:
        - success