---
kind: pipeline
type: docker
name: Build & Deploy GUI
concurrency:
  limit: 1
platform:
  os: linux
  arch: amd64
steps:
  - name: build
    image: node
    volumes:
      - name: release
        path: /release
    commands:
      - yarn | sed $'s,\x1b\\[[0-9;]*[a-zA-Z],,g'
      - yarn run build | sed $'s,\x1b\\[[0-9;]*[a-zA-Z],,g'
      - rm -rf /release/assets/
      - cp -r dist/* /release/
      - chmod -R 775 /release/*
    when:
      branch:
        - master
      status:
        - success

volumes:
  - name: release
    host:
      path: /opt/www/audio